# https://realm.github.io/SwiftLint/rule-directory.html
# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - trailing_whitespace
  - xctfail_message
  - function_parameter_count
  - weak_delegate
  - switch_case_alignment
  - type_body_length
  - file_length
  - nesting
# remove follow rules after analyze
  - todo
  - unused_setter_value
  - cyclomatic_complexity
  - notification_center_detachment  
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # Find all the available rules by running: `swiftlint rules`
  - sorted_imports

# Alternatively, specify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace

included: # paths to include during linting. `--path` is ignored if present.
  - SnazzyList
  - ../SnazzyList
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
# line_length: 110
# they can set both implicitly with an array
# or they can set both explicitly
large_tuple:
  warning: 5
  error: 10
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 200
    error: 300
  excluded:
    - iPhone # excluded via string
    - API
  allowed_symbols: ["_"] # these are allowed in type names
function_body_length:
  warning: 100
  error: 150
identifier_name:
  allowed_symbols: ["_"] # these are allowed in type names
  min_length: # only min_length
    error: 3 # only error
  max_length: 500
  excluded: # excluded via string array
    - vc
    - app
    - api
    - id
    - ids
    - url
    - URL
    - all
    - sut
    - key
    - i
    - j
    - day
    - min
    - sec
    - max
    - hex
    - by
    - from
    - now
    - hud
    - lhs
    - rhs
    - low
    - tab
    - loc
    - pan
    - row
    - fax
    - exp
    - arm
    # from gists
    - mib
    - API
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
