source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'SnazzyList_Example' do
  use_frameworks!
  
  pod 'SnazzyList', :path => '../'
  
  target 'SnazzyList_Tests' do
    inherit! :search_paths
    
    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
