source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'SnazzyList_Example' do
  use_frameworks!
  
  pod 'SnazzyList', :path => '../'
  
  
  target 'SnazzyList_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
